language: ruby

rvm:
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
  - jruby-head

sudo: false

addons:
  apt:
    packages:
    - libgmp3-dev

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

install:
  - gem install rainbow -v 2.2.1
  - bundle install

script: bundle exec rake

notifications:
  disable: true
